### ISSUE TITLE
Export Kepler.gl Trip Data

### ISSUE THREAD

**Issue by chrisgervang** [CodeLabs-Hubble-gl/kepler.gl#2]
[data.zip](https://github.com/CodeLabs-Hubble-gl/kepler.gl/files/4916882/data.zip) contains two files, raw input data and the resulting props captured using chrome dev tools source breakpoints. This `console.save` [snippet](http://bgrins.github.io/devtools-snippets/#console-save) was very helpful.

I'm pretty sure the datatype captured matches this propType of the MapContainer component.
https://github.com/CodeLabs-Hubble-gl/kepler.gl/blob/995024e86880fefb0624af4ed1e98d3879558336/src/components/map-container.js#L83-L86

<img width="1672" alt="Screen Shot 2020-07-13 at 11 08 39 PM" src="https://user-images.githubusercontent.com/2461547/87390500-d4244a80-c55d-11ea-9436-d622ca8e1d35.png">

**Comment by RaymondDashWu** [comment]
I was able to recreate the console part in Chrome but how do I access  e.mapState in React? It doesn't seem to be something simple like this.mapState or e.mapState
