### ISSUE TITLE
Create React state for attach/detach animation (based on random integer)

### ISSUE THREAD

**Issue by RaymondDashWu** [CodeLabs-Hubble-gl/kepler.gl#23]

**Comment by chrisgervang** [comment]
https://github.com/CodeLabs-Hubble-gl/kepler.gl/pull/17

https://luma.gl/docs/api-reference/engine/animation/timeline#attachanimationanimation-object-channelhandle--number--number

https://luma.gl/docs/api-reference/engine/animation/timeline#detachanimationhandle--number
