### ISSUE TITLE
Implement a setQuality function where the Deckgl canvas is hidden after the user clicks on render. Implement a loading UI function to be on the screen.

### ISSUE THREAD

**Issue by 97morningstar** [CodeLabs-Hubble-gl/kepler.gl#25]
To do:
- [ ] Research how to reuse the loading bar from kepler

**Comment by RaymondDashWu** [comment]
Separated into 2 tasks:
https://github.com/CodeLabs-Hubble-gl/hubble.gl/issues/42
https://github.com/CodeLabs-Hubble-gl/hubble.gl/issues/43
